name: ci

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Deno version
        run: deno --version

      - name: Run check
        run:
          "cd src/ && deno task check"