name: Set Pull Request

on:
  pull_request:
    types: [opened, edited]

jobs:
  set-pr:
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "not-reviewed, deno-deploy"
          remove-labels: "reviewed"
